require: rubocop-rails
AllCops:
  NewCops: enable
Layout/LineLength:
  Max: 125
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Documentation:
  Enabled: false